config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'

  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-inverse">
      <ul>
        <li><%= link_to 'One', pages_one_path %></li>
        <li><%= link_to 'Two', pages_two_path %></li>
        <li><%= link_to 'Three', pages_three_path %></li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Jerry Lewis</h1>

app/views/pages/three.html.erb
<h2>Hola Mundo</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>

<%= image_tag 'rails_routes.png' %>